name: Build

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - uses: actions/setup-python@v3

      - name: Run Docker build
        run: |
          DOCKER_SERVICE=manylinux-python311
          sudo docker-compose build ${DOCKER_SERVICE}
          sudo docker-compose run ${DOCKER_SERVICE}

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*.whl